name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  :contentReference[oaicite:0]{index=0}

      - name: Set up Java 11
        uses: actions/setup-java@v3  :contentReference[oaicite:1]{index=1}
        with:
          distribution: temurin
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3  :contentReference[oaicite:2]{index=2}
        with:
          name: MdSabirAli-App
          path: app/build/outputs/apk/debug/app-debug.apk
